#!/bin/bash

SOURCES="/tmp/firefox"
 
if [ -d $SOURCES ]
then
cd $SOURCES
else
mkdir $SOURCES
  cd $SOURCES
fi

echo "Downloading Firefox Source"
wget http://mozilla-mirror.3347.voxcdn.com/pub/mozilla.org/firefox/releases/latest/linux-i686/en-US/firefox-3.6.tar.bz2

echo "Removing existing Firefox installation"
sudo rm /usr/bin/firefox && sudo dpkg-divert --rename --remove /usr/bin/firefox && sudo rm -r /opt/firefox

echo "Installing new version of Firefox"
if [[ ! -f /usr/bin/firefox ]]; then sudo apt-get update && sudo apt-get install firefox; fi && if [[ -e ~/.mozilla ]]; then cp -R ~/.mozilla ~/.mozilla.backup; fi && sudo tar -jxvf firefox-3*.tar.bz2 -C /opt && rm firefox-3*.tar.bz2 && sudo mv /opt/firefox/plugins /opt/firefox/plugins.backup && sudo ln -s /usr/lib/xulrunner-addons/plugins /opt/firefox/plugins && sudo dpkg-divert --divert /usr/bin/firefox.ubuntu --rename /usr/bin/firefox && sudo ln -s /opt/firefox/firefox /usr/bin/firefox
 
echo "Removing cruft"
rm -rf $SOURCES
