#!/bin/bash

DOTVIM="/home/`whoami`/.vim"
JQUERY=12107
MULTIVALS=3582
GENUTILS=5663
DBEXT=11341
FUZZYFINDER=9643
TAGLIST=7701

if [ ! -e `which git` ]
then
  echo "You need git. Try running install_git"
  exit 0
fi

if [ ! -d $DOTVIM ]
then
  mkdir $DOTVIM
fi

get_repo() {
    gh_user=$1
    repo=$2
    echo "Checking $repo"
    if [ -d "$DOTVIM/bundle/$repo/" ]
    then
        echo "Pulling latest from $repo"
        cd $DOTVIM/bundle/$repo
        git pull origin master
        cd ..
    else
        echo "Cloning repo for $repo"
        git clone git://github.com/$gh_user/$repo.git
    fi
}

add_vimrc() {
    vimrc_file=$1
    vimrc_cmd=$2
    vimrc_file_path="/home/`whoami`/.$vimrc_file"
    
    echo "Checking to see if '$vimrc_cmd' has already been added to .$1"
    contains=`grep "$vimrc_cmd" $vimrc_file_path | wc -l`

    if [ $contains == 0 ]
    then
	echo "Hasn't been added, adding now."
	echo "$vimrc_cmd" >> $vimrc_file_path
    else
	echo "It was already added. Good to go"
    fi
}

echo "Copying .vimrc"
cp .vimrc $HOME

echo "Creating .vim folders if necessary"
mkdir -p $DOTVIM/{autoload,bundle,ruby}
cd $DOTVIM/bundle/

tpope_repos=(rails haml git cucumber fugitive vividchalk surround unimpaired abolish repeat endwise)

for r in ${tpope_repos[*]}; do
	repo="vim-$r"
    get_repo "tpope" $repo
done

echo "Installing NERDTree"
get_repo "scrooloose" "nerdtree"

echo "Installing NERDCommenter"
get_repo "scrooloose" "nerdcommenter"

echo "Installing snipMate"
get_repo "msanders" "snipmate.vim"

echo "Installing vim-ruby"
get_repo "vim-ruby" "vim-ruby"

if [ ! -d "$DOTVIM/bundle/vim-ruby-debugger" ]
then
  echo "Cleaning up vim-ruby-debugger"
  rm -rf $DOTVIM/bundle/vim-ruby-debugger/{bin,doc,plugin}
fi
echo "Installing vim-ruby-debugger"
get_repo "astashov" "vim-ruby-debugger"
mkdir $DOTVIM/bundle/vim-ruby-debugger/bin
cp $DOTVIM/bundle/vim-ruby-debugger/vim/bin/ruby_debugger.rb $DOTVIM/bundle/vim-ruby-debugger/bin
mkdir $DOTVIM/bundle/vim-ruby-debugger/doc
cp $DOTVIM/bundle/vim-ruby-debugger/vim/doc/ruby_debugger.txt $DOTVIM/bundle/vim-ruby-debugger/doc
mkdir $DOTVIM/bundle/vim-ruby-debugger/plugin
cp $DOTVIM/bundle/vim-ruby-debugger/vim/plugin/ruby_debugger.vim $DOTVIM/bundle/vim-ruby-debugger/plugin

echo "Installing jQuery"
mkdir -p jquery/syntax
wget -c -O jquery/syntax/jquery.vim http://www.vim.org/scripts/download_script.php?src_id=$JQUERY

echo "Installing multivals"
mkdir multivals
wget -c -O multivals/multivals.vim http://www.vim.org/scripts/download_script.php?src_id=$MULTIVALS

echo "Installing genutils"
mkdir genutils
wget -c -O genutils/genutils.vim http://www.vim.org/scripts/download_script.php?src_id=$GENUTILS

echo "Installing fuzzyfinder"
mkdir -p fuzzyfinder/plugin
wget -c -O fuzzyfinder/plugin/fuzzyfinder.vim http://www.vim.org/scripts/download_script.php?src_id=$FUZZYFINDER

echo "Installing fuzzyfinder-textmate"
mkdir -p fuzzyfinder-textmate/plugin
wget -c -O fuzzyfinder-textmate/plugin/fuzzyfinder_textmate.vim http://github.com/jamis/fuzzyfinder_textmate/raw/b9d541db520268aa6c7e2cb29effe66e05a4d72b/fuzzyfinder_textmate.vim
wget -c -O $DOTVIM/ruby/fuzzy_file_finder.rb http://github.com/jamis/fuzzy_file_finder/raw/master/lib/ruzzy_file_finder.rb

echo "Installing supertab"
mkdir -p supertab/doc
mkdir -p supertab/plugin
wget -c -O supertab/doc/supertab.txt http://github.com/ervandew/vimfiles/raw/master/vim/doc/supertab.txt
wget -c -O supertab/plugin/supertab.vim http://github.com/ervandew/vimfiles/raw/bc2af1ee3c8d8c077ecf342bbf55635bec56562b/vim/plugin/supertab.vim

echo "Installing taglist"
rm -rf taglist
mkdir taglist
cd taglist
wget -c -O taglist.zip http://www.vim.org/scripts/download_script.php?src_id=$TAGLIST
unzip -a taglist.zip
rm taglist.zip
cd ..

# Make sure this is the last plugin to be installed
echo "Installing dbext"
rm -rf dbext
mkdir dbext
cd dbext
wget -c -O dbext.zip http://www.vim.org/scripts/download_script.php?src_id=$DBEXT
unzip -a dbext.zip
rm dbext.zip

cd $DOTVIM/autoload
echo "Fetching latest pathogen.vim"
rm pathogen.vim
# Fetching directly from the URL because pathogen must be installed in autoload
wget http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim

add_vimrc "gvimrc" "colorscheme vividchalk" 
