#!/bin/bash

echo "Installing pre-requisites"
yum install -y gcc-c++
yum install -y patch
yum install -y zlib-devel
yum install -y openssl-devel
yum install -y readline-devel.x86_64
yum install -y sqlite-devel.x86_64

SOURCES="/tmp/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

## Install Ruby Enterprise Edition
#
echo "Installing Ruby Enterprise Edition"
wget http://rubyforge.org/frs/download.php/68719/ruby-enterprise-1.8.7-2010.01.tar.gz
tar xzvf ruby-enterprise-1.8.7-2010.01.tar.gz
./ruby-enterprise-1.8.7-2010.01/installer

ln -s /opt/ruby-enterprise-1.8.7-2010.01 /opt/ruby-enterprise
ln -s /opt/ruby-enterprise/bin/ruby /usr/bin/ruby
ln -s /opt/ruby-enterprise/bin/gem /usr/bin/gem
ln -s /opt/ruby-enterprise/bin/irb /usr/bin/irb

echo "Updating /etc/profile"
echo "export PATH=/opt/ruby-enterprise/bin:\$PATH" >> /etc/profile
source /etc/profile

echo "Installing Phusion Passenger for nginx"
/opt/ruby-enterprise/bin/passenger-install-nginx-module
