#!/bin/bash

echo "Adding the repos to /etc/apt/sources.list.d/"

sudo sh -c 'echo "deb http://ppa.launchpad.net/pdoes/ppa/ubuntu karmic main
deb-src http://ppa.launchpad.net/pdoes/ppa/ubuntu karmic main" > /etc/apt/sources.list.d/pdoes.list'

# Add keys
 
#Pdoes
# 4CBEDD5A
 
echo "Adding the PPA keys"
for i in 4CBEDD5A;
do
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $i
done
 
# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get install git-core git-doc git-arch vim exuberant-ctags vim-gnome cscope build-essential libssl-dev libreadline5-dev zlib1g-dev checkinstall sqlite3 libsqlite3-dev


# Install Ruby 1.8.7

RUBY="ruby-1.8.7-p249"
RUBYGEMS="rubygems-1.3.5"
SOURCES="/home/`whoami`/Sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

echo "Downloading $RUBY"
wget -c ftp://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY.tar.gz
tar xzf $RUBY.tar.gz
cd $RUBY/
echo "Configuring, making and installing $RUBY"
./configure
make
sudo checkinstall

echo "Validating $RUBY installation"
ruby -v
ruby -ropenssl -rzlib -rreadline -e "puts 'Viva Railstutor'"

cd $SOURCES
echo "Downloading $RUBYGEMS"
wget http://rubyforge.org/frs/download.php/60718/$RUBYGEMS.tgz
tar xzf $RUBYGEMS.tgz
cd $RUBYGEMS/
sudo ruby setup.rb
gem -v
sudo gem update --system

cd $SOURCES
echo "Installing sqlite3 gem"
sudo gem install sqlite3-ruby

echo "Installing ruby-debug-ide"
sudo gem install ruby-debug-ide

echo "Installing Rails"
sudo gem install rails
