#!/bin/bash


sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu maverick main
deb-src http://linux.dropbox.com/ubuntu maverick main" > /etc/apt/sources.list.d/dropbox.list'

# Add keys
echo "Adding the dropbox public key to our keyring"
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get install nautilus-dropbox

